In [3]:
import numpy as np          

In [7]:
num1 = int(input('Enter the dimension 1 positive integer numbers between 5 to 20, ='))
num2 = int(input('Enter the dimension 2 positive integer numbers between 5 to 20, ='))

x = np.zeros((num1,num2))

 
        
x[1:-1,1:-1] = 1
print(x)


Enter the dimension 1 positive integer numbers between 5 to 20, =5
Enter the dimension 2 positive integer numbers between 5 to 20, =5
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [8]:
for i in range(num1): 
        for j in range(num2): 
            print(x[i][j], end =" ")  
        print()

0.0 0.0 0.0 0.0 0.0 
0.0 1.0 1.0 1.0 0.0 
0.0 1.0 1.0 1.0 0.0 
0.0 1.0 1.0 1.0 0.0 
0.0 0.0 0.0 0.0 0.0 
